FEATURES = [
    {
        "id": "P01",
        "name": "ret_1",
        "category": "price",
        "expression": "close / LAG(close, 1) OVER (ORDER BY timestamp) - 1",
        "depends_on": [],
    },
    {
        "id": "P02",
        "name": "ret_3",
        "category": "price",
        "expression": "close / LAG(close, 3) OVER (ORDER BY timestamp) - 1",
        "depends_on": [],
    },
    {
        "id": "P03",
        "name": "ret_6",
        "category": "price",
        "expression": "close / LAG(close, 6) OVER (ORDER BY timestamp) - 1",
        "depends_on": [],
    },
    {
        "id": "O01",
        "name": "oi_ret_1",
        "category": "oi",
        "expression": "oi / LAG(oi, 1) OVER (ORDER BY timestamp) - 1",
        "depends_on": [],
    },
    {
        "id": "F01",
        "name": "funding_z",
        "category": "funding",
        "expression": "(funding - _funding_rm180) / (_funding_rs180 + 0.00000001)",
        "depends_on": ["_funding_rm180", "_funding_rs180"],
    },
    {
        "id": "L01",
        "name": "liq_total",
        "category": "liquidation",
        "expression": "long_liq + short_liq",
        "depends_on": [],
    },
    {
        "id": "L02",
        "name": "liq_shock",
        "category": "liquidation",
        "expression": "liq_total / (_liq_rm180 + 0.00000001)",
        "depends_on": ["liq_total", "_liq_rm180"],
    },
]
